// LobbyManagerTests.cs
//
// Note: LobbyManager's constructor requires IMultiplayerController, an IL2CPP interop
// interface generated by BepInEx from the game binary. It cannot be implemented or mocked
// in managed code outside the game runtime, so state-machine tests (JoinRoomByInvite,
// HandleJoinedRoom, HandleLeftRoom, etc.) require in-game integration testing.
//
// The tests below cover only the method that is fully exercisable in a plain .NET test
// process: IsValidRoomName (a pure static method with no IL2CPP dependency).

using EKLobbyMod;
using Xunit;

namespace EKLobbyMod.Tests;

public class LobbyManagerTests
{
    // IsValidRoomName tests

    [Fact]
    public void IsValidRoomName_NullReturnsFalse()
    {
        Assert.False(LobbyManager.IsValidRoomName(null));
    }

    [Fact]
    public void IsValidRoomName_EmptyReturnsFalse()
    {
        Assert.False(LobbyManager.IsValidRoomName(""));
    }

    [Fact]
    public void IsValidRoomName_65CharsReturnsFalse()
    {
        Assert.False(LobbyManager.IsValidRoomName(new string('A', 65)));
    }

    [Fact]
    public void IsValidRoomName_64CharsReturnsTrue()
    {
        Assert.True(LobbyManager.IsValidRoomName(new string('A', 64)));
    }

    [Fact]
    public void IsValidRoomName_SlashReturnsFalse()
    {
        Assert.False(LobbyManager.IsValidRoomName("EK/HOME"));
    }

    [Fact]
    public void IsValidRoomName_BackslashReturnsFalse()
    {
        Assert.False(LobbyManager.IsValidRoomName("EK\\HOME"));
    }

    [Fact]
    public void IsValidRoomName_DotReturnsFalse()
    {
        Assert.False(LobbyManager.IsValidRoomName("EK.HOME"));
    }

    [Fact]
    public void IsValidRoomName_ValidRoomCodeReturnsTrue()
    {
        // Typical room code format used by the game
        Assert.True(LobbyManager.IsValidRoomName("EK-A3F9C12B"));
    }

    [Fact]
    public void IsValidRoomName_NonAsciiReturnsFalse()
    {
        // Character above U+007E: must be rejected
        Assert.False(LobbyManager.IsValidRoomName("EK-café"));
    }

    [Fact]
    public void IsValidRoomName_ControlCharReturnsFalse()
    {
        // SOH (U+0001) is below 0x20: must be rejected
        Assert.False(LobbyManager.IsValidRoomName("EK-\x01HOME"));
    }
}
